spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

app:
  kafka:
    user-topic: user.account

server:
  port: 8080

springdoc:
  packages-to-scan: org.example.userdbapi.controller
  paths-to-match: /api/**

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: INFO

