server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info